[[MDAL]]
arch = "aarch64"
git-tree-sha1 = "5114bb8b00c2c9ef053b548c4ce51be585450b2c"
os = "macos"

    [[MDAL.download]]
    sha256 = "8efd6770e6dee69883c0919981f7528d32e2bb5578d81d1d0d78506f2a0180c0"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.aarch64-apple-darwin.tar.gz"
[[MDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "553d30c68e75956f419d010ea484c168534ca3fd"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "d1e5d429a230e77fdf33f4dd3b2431c92e14144821b08a5e5277a560d07935c4"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.aarch64-linux-gnu-cxx03.tar.gz"
[[MDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1be56921323f0bc1bdc33a2f12a7b90c99b98c22"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "437732c6581e468c3297fc7fe49487f4949e0b7086a650067d62493437ee4bda"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.aarch64-linux-gnu-cxx11.tar.gz"
[[MDAL]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "119a23373ceb9f464840e6a8e347556c81c26f24"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "6e4f4026cdfc76042019df62d078b908adbd89bc4330927956022a7b23e102d0"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.aarch64-linux-musl-cxx03.tar.gz"
[[MDAL]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed838bdee33eba26d731c54f21537cc67cdbc37f"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "7f55ff2ae59e6ccfa758437213d9fe7e990849e367263bcec0aa28bb882454e1"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.aarch64-linux-musl-cxx11.tar.gz"
[[MDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "728e00b3a2d70f26df27674670d4ef5254ab2249"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "d7e764339c4b0668d477d782843bbe6505ff7ea95b1870fa9c149e5f38ff73a4"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[MDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "21efa4e3fc4d318871caee937778e05310957dd7"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "58c7bca45d5b844f2a3a948b4c33cc7e33cb3af9426de7ebfb423ffc0b7f98db"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[MDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "895b33239255c93ce9875f386d76bd32bbda7f3f"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "048f2b9cfa13070135cd93a848d3090f3881bfec08e2190a9f72a219c8f671b5"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[MDAL]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "24d49f1eb26c618b3d0bd1ebbf59c0762018cfd5"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "b6518f096734a4ac75d70327f87cf605b90530533e6b044be1da9a735c7b0ced"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[MDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db34ed4a1cf50f68259906ed0bc5d3fb8e0417ad"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "ffa6485f2af131a0a6a39cd24c80ca7faf09cd8f6031151c2402aa6f95894697"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[MDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e411df2ed62cca9214b4f6f54d5e8ddc1d01bfd"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "b962fedf333a96011b51ff91638387f7e68997b3fe0af9defdf2fe3dc7ef2c21"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[MDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48210bbb16d7a06dd37134c66cce9e4c1a76724c"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "7792cebcc0942f02ee6f5c93859715cbcfb35523df3caaf56fb4cfcea1500437"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[MDAL]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94ada0b17b1bf7c378ed73d44a4cdf34d967263b"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "408e5197d066fa86c98edff77bc6fa8ad9ad620455476e92f0436eafc8eff13e"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[MDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b1dd7973a64a05020b5eceabe74206d46acb3ce8"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "dcd7c79acf0567b644483cffe60a3ededb359f2f565bbb310ff7a37559c3ec60"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.i686-linux-gnu-cxx03.tar.gz"
[[MDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b6c6b2b3fb00c5aac9b965dcd2c0d3a8eeb6154"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "55709ebaa5d290b7b3f620c80b12ffd81090c9fe6b0afd0fedb014c93b87fe7e"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.i686-linux-gnu-cxx11.tar.gz"
[[MDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "180f2a39f4a31c6e2253092da9b6df70c05103d4"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "fa8aa1fbcee6f61d68059be3f7cf4a511b26aa4a2bf345362fa9f176a5076203"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.i686-linux-musl-cxx03.tar.gz"
[[MDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b694830cbac0cf7416afa5b90dbd0fbb8588d52e"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "9540745a994701fa1ceb786a2d4285675052f7dbcc7fe3d999854654b1238dba"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.i686-linux-musl-cxx11.tar.gz"
[[MDAL]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f446aa3901705598602778a3c0b2b2f8e3c0cd6e"
os = "windows"

    [[MDAL.download]]
    sha256 = "021c7689b0aa62db9aca4637e435e451920f7760437702c386181266bda6abb1"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.i686-w64-mingw32-cxx03.tar.gz"
[[MDAL]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d8ed75740187c0b06e63a02bfc07f342f3adc02b"
os = "windows"

    [[MDAL.download]]
    sha256 = "eb2d5856636d2aeb6ec6827542a4753f7c87b3c724553f1add7a54d1734d4593"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.i686-w64-mingw32-cxx11.tar.gz"
[[MDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "15c0ab0e23883b6021dea73ec3d2735d06aff3e5"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "e78ae64bf64415a2d7063c8c243c343657a3b5da8aaa6840fc9ef1eae08d6a5c"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[MDAL]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0272a416fbf5a501c47abac5cdb936866b9a419f"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "78d58a0d383628ac3bd9a41bdff7d1f3ab9d223c2ed937404c831bf4b72664ec"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[MDAL]]
arch = "x86_64"
git-tree-sha1 = "900a989d9ba5c6787e5dbb941768d9807876cea8"
os = "macos"

    [[MDAL.download]]
    sha256 = "941eaf0aff12fb7a9b4b6a74235c66ff31a72748abfc0b447f7b270de03cff9b"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-apple-darwin.tar.gz"
[[MDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21b5003835675a5d044021151d514e53efe96d60"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "da0970811a923e816390671e09e3fce49e963b1b0518067681b7b54f0a7f4208"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-linux-gnu-cxx03.tar.gz"
[[MDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "786867692355478b4bc03fdb12fb380ea91f96b4"
libc = "glibc"
os = "linux"

    [[MDAL.download]]
    sha256 = "48d029afda15b303dbe07b39bc3f3827dfee6fc4b7d8316c8228b1b411c9c4b0"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-linux-gnu-cxx11.tar.gz"
[[MDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94c511e73b20f28de18afb4d3c10f4c4c468524b"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "ebe063082c35eeea30acd267ea1388aecda0107dd0c9afa8c9c1afedd4b03aea"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-linux-musl-cxx03.tar.gz"
[[MDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a9e50ed3432874b5226f756781bd35ff9c0334b"
libc = "musl"
os = "linux"

    [[MDAL.download]]
    sha256 = "5f3fc5e2c87b01fd0ad76044b225fac1335b583f5bc32c234c3a490c3cdd667d"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-linux-musl-cxx11.tar.gz"
[[MDAL]]
arch = "x86_64"
git-tree-sha1 = "9e700cac7398d196173579dd30031a87ff6bd451"
os = "freebsd"

    [[MDAL.download]]
    sha256 = "8f7c81c2ed4d73ab38285fe6beb56ca0f4671406c17076d5453b3ce77fc32257"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-unknown-freebsd.tar.gz"
[[MDAL]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3789b6f227be5e4a41cd4f82b04c0af445727bb"
os = "windows"

    [[MDAL.download]]
    sha256 = "339fec55237f81346092d264a79e371be2d70b99dff2170dc2efe5831a69edb5"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[MDAL]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9be191549d601eebd24702a9482eb77e6d888215"
os = "windows"

    [[MDAL.download]]
    sha256 = "31b99bca4833dd218bc5d82166fbfce6f0d99985531d5d176d1578bcaa12282b"
    url = "https://github.com/JuliaBinaryWrappers/MDAL_jll.jl/releases/download/MDAL-v0.9.4+0/MDAL.v0.9.4.x86_64-w64-mingw32-cxx11.tar.gz"
